name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Run tests (root)
      run: cargo test --verbose

    - name: Run tests (typesafe_builder_derive)
      run: |
        cd typesafe_builder_derive
        cargo test --verbose

    - name: Check formatting (typesafe_builder_derive)
      run: |
        cd typesafe_builder_derive
        cargo fmt --all -- --check

    - name: Run clippy (typesafe_builder_derive)
      run: |
        cd typesafe_builder_derive
        cargo clippy -- -D warnings
